"""ComplyAgent — Streamlit dashboard.

Reads the most recent eval artifact at outputs/latest-eval.json and renders a
multi-tab demo. By design this dashboard does not hit the Gemini API; it
displays the most recent pre-computed eval, which is regenerated by
`uv run python scripts/run_eval.py <tenant>` and committed to the repo.

That choice is deliberate: a public demo URL where every visitor triggered
fresh classification would burn the shared free-tier quota in minutes and
make eval numbers non-deterministic.
"""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import streamlit as st
import yaml

PROJECT_ROOT = Path(__file__).resolve().parent
DEFAULT_TENANT_SLUG = "hyperswitch"

st.set_page_config(
    page_title="ComplyAgent — repo-connected compliance agent",
    page_icon="📑",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ----------------------------------------------------------------------------
# Loaders (cached for cheap re-render)
# ----------------------------------------------------------------------------

@st.cache_data(show_spinner=False)
def load_yaml(path: Path) -> dict:
    return yaml.safe_load(path.read_text()) or {}


@st.cache_data(show_spinner=False)
def load_json(path: Path) -> dict:
    return json.loads(path.read_text())


@st.cache_data(show_spinner=False)
def load_text(path: Path) -> str:
    return path.read_text()


@st.cache_data(show_spinner=False)
def load_tenants() -> list[str]:
    tdir = PROJECT_ROOT / "tenants"
    if not tdir.exists():
        return []
    return sorted(p.name for p in tdir.iterdir() if p.is_dir())


def load_latest_eval(tenant_slug: str) -> dict | None:
    """Prefer the per-tenant latest pointer if present, else fall back to the
    most recent timestamped eval file for this tenant."""
    out_dir = PROJECT_ROOT / "outputs"
    if not out_dir.exists():
        return None
    latest = out_dir / "latest-eval.json"
    if latest.exists():
        data = load_json(latest)
        if data.get("tenant") == tenant_slug:
            return data
    matches = sorted(out_dir.glob(f"eval-{tenant_slug}-*.json"), reverse=True)
    if matches:
        return load_json(matches[0])
    return None


# ----------------------------------------------------------------------------
# Sidebar — tenant selector + summary
# ----------------------------------------------------------------------------

with st.sidebar:
    st.markdown("### ComplyAgent")
    st.caption("Repo-connected compliance agent for payments codebases")

    tenants = load_tenants()
    if not tenants:
        st.error("No tenants found under `tenants/`. Did you clone the full repo?")
        st.stop()
    tenant_slug = st.selectbox(
        "Tenant",
        tenants,
        index=tenants.index(DEFAULT_TENANT_SLUG) if DEFAULT_TENANT_SLUG in tenants else 0,
        help="In v0 there's one tenant — but the pipeline reads per-tenant config so adding a second is a config drop, not a code change.",
    )

    tenant_cfg = load_yaml(PROJECT_ROOT / "tenants" / tenant_slug / "config.yaml")
    profile = load_yaml(PROJECT_ROOT / "tenants" / tenant_slug / "product_profile.yaml")

    t_info = tenant_cfg.get("tenant", {})
    codebase = tenant_cfg.get("codebase", {})
    st.markdown(f"**{t_info.get('display_name', tenant_slug)}**")
    if codebase.get("repo"):
        st.markdown(f"`{codebase['repo']}`")
    st.caption(t_info.get("description", ""))

    st.divider()
    st.markdown("##### Author")
    st.markdown(
        "[Karthik Subramaniam](https://www.linkedin.com/in/karthikeyans/) — "
        "Senior PM portfolio, June 2026"
    )
    st.markdown("[Source on GitHub](https://github.com/karthikeyan-smg1/complyagent)")


# ----------------------------------------------------------------------------
# Header
# ----------------------------------------------------------------------------

st.title("ComplyAgent")
st.markdown(
    "**Repo-connected compliance agent for payments codebases.** "
    "Reads card-network and central-bank bulletins, decides which ones require "
    "code changes in a target payments codebase, drafts an impact assessment, "
    "and proposes engineering tickets — in the engineering team's own backlog."
)

eval_data = load_latest_eval(tenant_slug)
if not eval_data:
    st.warning(
        "No eval artifact found yet under `outputs/`. Run "
        f"`uv run python scripts/run_eval.py {tenant_slug}` to generate one."
    )
    st.stop()


metrics = eval_data.get("metrics", {})
results = eval_data.get("results", [])
run_at = eval_data.get("run_at_utc", "—")


# Top-of-page strip with the four headline metrics
m1, m2, m3, m4 = st.columns(4)
with m1:
    st.metric("Bulletins evaluated", metrics.get("labeled", 0))
with m2:
    val = metrics.get("precision")
    st.metric("Precision (relevant)", f"{val:.0%}" if val is not None else "—")
with m3:
    val = metrics.get("recall")
    st.metric("Recall (relevant)", f"{val:.0%}" if val is not None else "—")
with m4:
    val = metrics.get("f1")
    st.metric("F1", f"{val:.2f}" if val is not None else "—")
st.caption(f"Latest eval run: `{run_at}` UTC — tenant `{tenant_slug}`. "
           "Results are pre-computed and committed; the dashboard does not "
           "hit the LLM API on page load.")


# ----------------------------------------------------------------------------
# Tabs
# ----------------------------------------------------------------------------

tab_overview, tab_inbox, tab_eval, tab_design, tab_roadmap, tab_about = st.tabs(
    ["Overview", "Bulletin inbox", "Evaluation", "Design", "Roadmap", "About"]
)


# ----------------------------------------------------------------------------
# Tab: Overview
# ----------------------------------------------------------------------------

with tab_overview:
    st.markdown("## The problem")
    st.markdown(
        "Card networks (Visa, Mastercard, RuPay, Amex) and central banks publish "
        "hundreds of operational and regulatory bulletins each quarter. Payments "
        "engineering teams must triage them: figure out which bulletins require "
        "code changes in their stack, by what date, in which subsystem, and what "
        "a draft fix looks like.\n\n"
        "Most teams do this manually — a senior engineer spends a Monday morning "
        "every week reading bulletins and filing tickets. It is slow, "
        "inconsistent, and the highest-leverage bulletins (a Visa mandate with a "
        "3-month deadline, an RBI directive with a daily compliance fee) are the "
        "ones most likely to be missed or filed late."
    )

    st.markdown("## What ComplyAgent does")
    st.markdown(
        "1. **Ingests bulletins** — curated set of Visa bulletins in v0, "
        "extensible by dropping markdown files into `tenants/<slug>/bulletins/`.\n"
        "2. **Classifies relevance in two stages** — Gemini 2.5 Flash tags the "
        "bulletin against a payments taxonomy (network, topic, action type, "
        "effective date, mandatory yes/no); a second Gemini call decides "
        "whether the bulletin requires code changes in the target codebase, "
        "grounded in a tenant-specific product profile.\n"
        "3. **Drafts an impact assessment and engineering ticket** — code-RAG "
        "over the target repo finds the modules likely affected; a third LLM "
        "call drafts a ticket with severity, deadline, and proposed code-change "
        "outline. *(v0.2 — not yet shipped in this commit; see Roadmap.)*\n"
        "4. **Reviews itself** — every classification cites specific language "
        "from the bulletin and specific surfaces from the product profile; "
        "this is the eval handle, and the precision/recall numbers at the top "
        "of this page come from comparing those judgements against a "
        "hand-labeled ground truth."
    )

    st.markdown("## Pipeline at a glance")
    st.code(
        "Bulletin (markdown + YAML frontmatter)\n"
        "    ↓\n"
        "Stage 1: Gemini 2.5 Flash — tag (network / topic / action / effective_date / mandatory)\n"
        "    ↓\n"
        "Stage 2: Gemini 2.5 Flash — relevance vs product profile → {relevant, confidence, reasoning, affected_surfaces}\n"
        "    ↓ (if relevant — v0.2)\n"
        "Code RAG: Voyage code embeddings + pgvector → top-k code chunks\n"
        "    ↓\n"
        "Stage 3: Impact assessment → draft analysis + affected files\n"
        "    ↓\n"
        "Priority rubric (deterministic) → P0..P3\n"
        "    ↓\n"
        "GitHub Issue created on the target repo fork",
        language="text",
    )

    st.markdown("## Why this artifact exists")
    st.markdown(
        "This is a portfolio prototype, deliberately scoped tight. The point is "
        "to demonstrate product thinking around AI-agent design for a real, "
        "expensive enterprise problem: clear scoping, tenant-shaped "
        "architecture even at single-tenant size, an evaluable "
        "riskiest-assumption test before any UX work, and an explicit "
        "scaling path for both SaaS and on-prem enterprise deployments. "
        "See the **Design** tab for the load-bearing decisions and the "
        "**Roadmap** tab for what's deliberately deferred."
    )


# ----------------------------------------------------------------------------
# Tab: Bulletin inbox
# ----------------------------------------------------------------------------

with tab_inbox:
    st.markdown("## Bulletin inbox")
    st.markdown(
        "Every bulletin the agent has classified for this tenant. Filter by "
        "predicted relevance; click a row to expand reasoning and tags."
    )

    rows: list[dict] = []
    for r in results:
        tags = r.get("tags") or {}
        rel = r.get("relevance") or {}
        rows.append({
            "bulletin_id": r["bulletin_id"],
            "title": r.get("title", ""),
            "network": tags.get("network", "—"),
            "topic": tags.get("topic", "—"),
            "action_type": tags.get("action_type", "—"),
            "mandatory": "yes" if tags.get("mandatory") else "no",
            "effective_date": tags.get("effective_date") or "—",
            "predicted_relevant": rel.get("relevant"),
            "expected_relevant": r.get("expected_relevance"),
            "confidence": rel.get("confidence"),
            "affected_surfaces": ", ".join(rel.get("affected_surfaces", [])) or "—",
            "error": r.get("error", ""),
        })
    df = pd.DataFrame(rows)

    col_f1, col_f2, col_f3 = st.columns([1, 1, 2])
    with col_f1:
        filter_pred = st.selectbox(
            "Predicted",
            ["All", "Relevant only", "Not relevant only"],
            index=0,
        )
    with col_f2:
        filter_net = st.selectbox(
            "Network",
            ["All"] + sorted(df["network"].dropna().unique().tolist()),
            index=0,
        )
    with col_f3:
        search = st.text_input("Search title or ID", value="").strip().lower()

    view = df.copy()
    if filter_pred == "Relevant only":
        view = view[view["predicted_relevant"].astype(bool)]
    elif filter_pred == "Not relevant only":
        view = view[~view["predicted_relevant"].astype(bool)]
    if filter_net != "All":
        view = view[view["network"] == filter_net]
    if search:
        view = view[
            view["title"].str.lower().str.contains(search, na=False)
            | view["bulletin_id"].str.lower().str.contains(search, na=False)
        ]

    show_df = view[[
        "bulletin_id", "title", "network", "topic", "action_type",
        "mandatory", "predicted_relevant", "confidence", "affected_surfaces",
    ]].rename(columns={
        "predicted_relevant": "Predicted relevant",
        "confidence": "Confidence",
        "affected_surfaces": "Affected surfaces",
    })

    st.dataframe(
        show_df,
        hide_index=True,
        use_container_width=True,
        column_config={
            "Predicted relevant": st.column_config.CheckboxColumn(),
            "Confidence": st.column_config.ProgressColumn(min_value=0, max_value=1, format="%.2f"),
        },
    )

    st.markdown("### Bulletin detail")
    if len(view):
        selected_id = st.selectbox(
            "Inspect a bulletin",
            view["bulletin_id"].tolist(),
            index=0,
        )
        rec = next((r for r in results if r["bulletin_id"] == selected_id), None)
        if rec:
            c1, c2 = st.columns([2, 3])
            with c1:
                tags = rec.get("tags") or {}
                rel = rec.get("relevance") or {}
                st.markdown(f"**{rec.get('title', selected_id)}**")
                st.caption(f"`{selected_id}` · {rec.get('file', '')}")
                st.markdown(
                    f"- **Network:** {tags.get('network', '—')}\n"
                    f"- **Topic:** {tags.get('topic', '—')}\n"
                    f"- **Action type:** {tags.get('action_type', '—')}\n"
                    f"- **Mandatory:** {'yes' if tags.get('mandatory') else 'no'}\n"
                    f"- **Effective date:** {tags.get('effective_date') or '—'}\n"
                    f"- **Predicted relevant:** {rel.get('relevant')} "
                    f"(confidence {rel.get('confidence', 0):.2f})\n"
                    f"- **Expected (ground truth):** {rec.get('expected_relevance') or '—'} "
                    f"({rec.get('expected_priority') or '—'})\n"
                    f"- **Affected surfaces:** "
                    f"{', '.join(rel.get('affected_surfaces', [])) or '—'}"
                )
                if rec.get("error"):
                    st.error(rec["error"])
            with c2:
                st.markdown("**Stage-2 reasoning**")
                reasoning = rec.get("relevance", {}).get("reasoning", "—")
                st.info(reasoning)

                bulletin_path = PROJECT_ROOT / rec.get("file", "")
                if bulletin_path.exists():
                    with st.expander("View bulletin source"):
                        st.markdown(load_text(bulletin_path))


# ----------------------------------------------------------------------------
# Tab: Evaluation
# ----------------------------------------------------------------------------

with tab_eval:
    st.markdown("## Classifier evaluation")
    st.markdown(
        "Eval framework: each bulletin in the corpus carries a hand-labeled "
        "`expected_relevance` in its frontmatter. The classifier runs over the "
        "full corpus; precision / recall / F1 are computed against those "
        "labels with `relevant` as the positive class."
    )

    g1, g2, g3, g4 = st.columns(4)
    with g1:
        st.metric("True positives", metrics.get("true_positive", 0))
    with g2:
        st.metric("False positives", metrics.get("false_positive", 0))
    with g3:
        st.metric("True negatives", metrics.get("true_negative", 0))
    with g4:
        st.metric("False negatives", metrics.get("false_negative", 0))

    st.markdown("### Confusion matrix")
    cm = pd.DataFrame(
        {
            "Predicted relevant": [
                metrics.get("true_positive", 0),
                metrics.get("false_positive", 0),
            ],
            "Predicted not relevant": [
                metrics.get("false_negative", 0),
                metrics.get("true_negative", 0),
            ],
        },
        index=["Actually relevant", "Actually not relevant"],
    )
    st.dataframe(cm, use_container_width=True)

    st.markdown("### Headline metrics")
    head = pd.DataFrame(
        {
            "Metric": ["Precision", "Recall", "F1", "Accuracy"],
            "Value": [
                metrics.get("precision"),
                metrics.get("recall"),
                metrics.get("f1"),
                metrics.get("accuracy"),
            ],
        }
    )
    head["Value"] = head["Value"].apply(
        lambda v: f"{v:.3f}" if isinstance(v, (int, float)) else "—"
    )
    st.dataframe(head, use_container_width=True, hide_index=True)

    st.markdown("### Per-bulletin verdicts")
    verdict_rows = []
    for r in results:
        if r.get("error"):
            verdict = "ERR"
        else:
            rel = r.get("relevance", {}).get("relevant")
            exp = r.get("expected_relevance")
            if exp == "relevant" and rel:
                verdict = "TP"
            elif exp == "not_relevant" and not rel:
                verdict = "TN"
            elif exp == "not_relevant" and rel:
                verdict = "FP"
            elif exp == "relevant" and not rel:
                verdict = "FN"
            else:
                verdict = "—"
        verdict_rows.append({
            "bulletin_id": r["bulletin_id"],
            "title": r.get("title", ""),
            "expected": r.get("expected_relevance") or "—",
            "predicted": r.get("relevance", {}).get("relevant"),
            "verdict": verdict,
            "confidence": r.get("relevance", {}).get("confidence"),
            "elapsed_s": r.get("elapsed_s"),
        })
    vdf = pd.DataFrame(verdict_rows)
    st.dataframe(vdf, hide_index=True, use_container_width=True)

    st.markdown(
        "**Eval limits.** The current corpus is small (10 bulletins, Visa only) "
        "and synthesized from public Visa programs — this is a sanity check on "
        "the two-stage architecture, not a SOTA claim. The next iteration "
        "expands to 30+ bulletins across Visa, Mastercard, and RBI, and adds "
        "borderline cases (opt-in regulatory programs, partial-jurisdiction "
        "rules) where calibration matters."
    )


# ----------------------------------------------------------------------------
# Tab: Design
# ----------------------------------------------------------------------------

with tab_design:
    st.markdown("## Load-bearing design decisions")
    st.markdown(
        "Each row links a v0 choice to its rationale. Full reasoning, "
        "alternatives considered, and anti-goals are in "
        "[`DECISIONS.md`](https://github.com/karthikeyan-smg1/complyagent/blob/main/DECISIONS.md)."
    )

    design_rows = [
        {
            "Decision": "Tenant-shaped single-tenant",
            "What it means": "Single-tenant for v0, but the pipeline reads "
                "a per-tenant `config.yaml` and `product_profile.yaml` — "
                "adding a tenant is a config drop, not a code change.",
            "Why": "Hiring managers need to see 'designed for SaaS from day "
                "one,' not 'built a demo and called it a prototype.' The "
                "tenancy structure is the differentiator.",
        },
        {
            "Decision": "Two-stage classifier (tag → judge)",
            "What it means": "Stage 1 picks taxonomy labels from a fixed "
                "enum schema; Stage 2 judges relevance against the product "
                "profile. Both stages use Gemini structured output "
                "(`response_schema`) so the contract is enforced at decode.",
            "Why": "Single-call 'is this relevant?' prompts hallucinate. "
                "Splitting tagging from judgement gives each step a "
                "narrower job, a clear failure mode, and a per-stage "
                "evaluable output.",
        },
        {
            "Decision": "Pre-computed eval artifacts in the dashboard",
            "What it means": "The dashboard renders from "
                "`outputs/latest-eval.json` committed to the repo. Live "
                "classification is gated behind a deliberate `Run eval` "
                "CLI invocation.",
            "Why": "A public demo URL where every visitor triggered fresh "
                "Gemini calls would burn the shared free-tier quota in "
                "minutes and make the numbers non-deterministic.",
        },
        {
            "Decision": "Gemini 2.5 Flash for both stages",
            "What it means": "Both Stage 1 and Stage 2 default to Flash. "
                "`COMPLY_STAGE2_MODEL=gemini-2.5-pro` swaps to Pro the "
                "moment billing is enabled.",
            "Why": "Gemini 2.5 Pro is paid-only — free-tier limit is 0 "
                "requests. Discovered during the first end-to-end run; "
                "fixed by swapping to Flash and making the model "
                "env-overridable. See DECISIONS.md 2026-06-06.",
        },
        {
            "Decision": "Hard timeouts + rate limiter on every LLM call",
            "What it means": "Every Gemini call has a 60s HTTP timeout, "
                "an 8-RPM global rate limiter, server-hint-aware retries, "
                "and a per-attempt progress event.",
            "Why": "Cost a 7-hour silent stall on the first run — the "
                "Google SDK honored a server `retryDelay` hint without a "
                "client timeout. Lesson: no long-running external call "
                "without a hard timeout and bounded retry.",
        },
    ]
    st.dataframe(pd.DataFrame(design_rows), hide_index=True, use_container_width=True)

    st.markdown("## What is deliberately out of scope")
    st.markdown(
        "- **Auth, billing, OAuth, secrets vault, multi-tenant DB isolation.** "
        "Named in the README as v1 SaaS scope with a recommended approach for "
        "each, not built. Hiring managers will not poke install flows; weeks "
        "spent there don't show in interviews.\n"
        "- **Network and central-bank corpora beyond Visa.** v0 is Visa-only. "
        "Extending to Mastercard / RBI / RuPay is a corpus-drop, not a code "
        "change — see the Roadmap tab.\n"
        "- **Real-time live demo of classification.** The Streamlit dashboard "
        "shows pre-computed results. Live classification is a CLI invocation, "
        "so the demo URL stays fast and deterministic."
    )


# ----------------------------------------------------------------------------
# Tab: Roadmap
# ----------------------------------------------------------------------------

with tab_roadmap:
    st.markdown("## v0.2 — closing the agent loop")
    st.markdown(
        "The current shipped slice classifies relevance. The next slice closes "
        "the loop end-to-end:\n\n"
        "1. **Code RAG over Hyperswitch** — chunk the target repo by Rust "
        "module boundary, embed via Voyage `voyage-code-3`, store in Supabase "
        "pgvector keyed on `(tenant_id, commit_sha)`.\n"
        "2. **Impact assessment LLM call** — bulletin + retrieved code chunks "
        "→ draft analysis + affected files list.\n"
        "3. **Deterministic priority rubric** — score from {mandatory yes/no, "
        "effective date proximity, affected-surface coverage} → P0..P3.\n"
        "4. **GitHub Issue created** on the Hyperswitch fork, populated with "
        "the impact draft, surface list, deadline, and proposed code-change "
        "outline. The dashboard surfaces issue links per bulletin.\n"
        "5. **GitHub Actions cron** runs the full pipeline weekly; commits "
        "refreshed `latest-eval.json` and the new issue references."
    )

    st.markdown("## Scaling — what the SaaS / on-prem extension looks like")
    st.markdown("### As a multi-tenant SaaS product")
    saas_rows = [
        {"Need": "Repo connection",
         "Recommended approach": "GitHub App install flow per tenant (vs cloned repo)"},
        {"Need": "Tracker connection",
         "Recommended approach": "Atlassian OAuth2 for Jira (vs GitHub Issues only)"},
        {"Need": "Tenant isolation",
         "Recommended approach": "Supabase RLS on every table, keyed on `tenant_id`"},
        {"Need": "Secrets at rest",
         "Recommended approach": "Supabase Vault or app-level KMS"},
        {"Need": "Scheduler",
         "Recommended approach": "One scheduler row per tenant; replace GH Actions cron with Temporal or Inngest"},
        {"Need": "Billing",
         "Recommended approach": "Per-tenant usage metering by bulletin count + LLM token spend; Stripe for collection"},
        {"Need": "Notifications",
         "Recommended approach": "Per-tenant Slack OAuth, email digest fallback"},
    ]
    st.dataframe(pd.DataFrame(saas_rows), hide_index=True, use_container_width=True)

    st.markdown("### For enterprise on-prem / airgapped customers")
    onprem_rows = [
        {"Concern": "Code and bulletins cannot leave the tenant's network",
         "Recommended approach": "Swappable provider interface; `LLMProvider=ollama` (Qwen 2.5 32B on ≥36GB nodes) and `Embedder=bge-m3` for embeddings"},
        {"Concern": "Vector store cannot be a cloud service",
         "Recommended approach": "Local Postgres + pgvector, or sqlite-vec for single-node deployments"},
        {"Concern": "Repo connection cannot be via GitHub.com",
         "Recommended approach": "Self-hosted GitLab / Bitbucket Server adapters behind the same `Repo` interface"},
        {"Concern": "Audit trail and source-of-truth provenance",
         "Recommended approach": "Tenant-local Langfuse instance + content-hash-keyed run journal"},
    ]
    st.dataframe(pd.DataFrame(onprem_rows), hide_index=True, use_container_width=True)
    st.caption(
        "Same `LLMProvider` and `Embedder` interfaces, swapped by env. "
        "Documented as an extension path, not built in v0."
    )


# ----------------------------------------------------------------------------
# Tab: About
# ----------------------------------------------------------------------------

with tab_about:
    st.markdown("## About this artifact")
    st.markdown(
        "ComplyAgent is a portfolio prototype by "
        "[Karthik Subramaniam](https://www.linkedin.com/in/karthikeyans/), "
        "Senior PM at Zuora (ex-Juspay), built over two weekends in June 2026. "
        "Goal: show senior-PM-level product thinking around a real AI-agent "
        "problem space — clear scoping, tenant-shaped architecture from day one, "
        "an evaluable riskiest-assumption test before any UX work, and an "
        "explicit scaling path for both SaaS and on-prem deployments.\n\n"
        "If you're hiring senior PMs and want to dig into the load-bearing "
        "decisions, the **Design** tab and "
        "[DECISIONS.md](https://github.com/karthikeyan-smg1/complyagent/blob/main/DECISIONS.md) "
        "are the right starting points."
    )
    st.markdown("### Stack")
    stack_rows = [
        {"Layer": "LLM", "Choice": "Google Gemini 2.5 Flash (both stages on free tier; Pro env-swap for billed keys)"},
        {"Layer": "Embeddings (v0.2)", "Choice": "Voyage AI `voyage-code-3` for code, `voyage-3-large` for documents"},
        {"Layer": "Vector store (v0.2)", "Choice": "Supabase Postgres + pgvector"},
        {"Layer": "Observability", "Choice": "Langfuse Cloud (free tier)"},
        {"Layer": "App hosting", "Choice": "Streamlit Community Cloud"},
        {"Layer": "Scheduled runs (v0.2)", "Choice": "GitHub Actions cron"},
        {"Layer": "Secrets", "Choice": "`.env` locally, Streamlit Cloud secrets in prod"},
    ]
    st.dataframe(pd.DataFrame(stack_rows), hide_index=True, use_container_width=True)

    st.markdown("### Links")
    st.markdown(
        "- [Source on GitHub](https://github.com/karthikeyan-smg1/complyagent)\n"
        "- [BRIEF.md — scope and anti-goals](https://github.com/karthikeyan-smg1/complyagent/blob/main/BRIEF.md)\n"
        "- [DECISIONS.md — design rationale](https://github.com/karthikeyan-smg1/complyagent/blob/main/DECISIONS.md)\n"
        "- [Karthik on LinkedIn](https://www.linkedin.com/in/karthikeyans/)"
    )
